### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by ToastedDev** [NotTCA/PainBot#1]
# To-do list
This is the official to-do list for this PainBot rewrite.

# Commands
- [x] Moderation commands (kick, ban, ...)
- [x] Dynamic help command with dropdown menu
- [x] Better ping command
- [x] Say command [(as requested by g8speedy)](https://tca.is-from.space/r/Discord_B0U1qOEpwS.png)
# Features
- [ ] Welcomer and leaver
- [x] Guild-specific prefixes
- [x] Random status
- [ ] Reaction roles
- [ ] Auto moderation
# Other
- [ ] Fix >whowouldwin bug where you can fight yourself

**Comment by ToastedDev** [comment]
We have a new to-do list. Check it out [here](https://github.com/TCATech/PainBot/projects).
